### ISSUE TITLE
Issue: missing E75_bed.tsv file 

### ISSUE THREAD

**Issue by jacobljh** [ding-lab/misplice#1]
## Description

I'm trying to reproduce the result, but when it comes to the **in_silico_ns.control.v4.pl** script, I noticed that there was a missing file on **line 24**, which should be **resource/E75_bed.tsv**. And the file is nowhere to be found, neither in the paper nor under this repository.

It'd be greatly appreciated if you could provide a way to get this file.

**Comment by reykajayasinghe** [comment]
Unfortunately we could not upload the E75 bed file to the github repository because it is large. You can download gene annotation files from many resources.

The bed file should look something like below for Homo Sapiens but there are many other gene annotations files available here depending on your needs (http://useast.ensembl.org/info/data/ftp/index.html - Homo_sapiens.GRCh37.75.gtf):
chr1	11868	12226	DDX11L1:ENST00000456328:+:e1
chr1	11871	12226	DDX11L1:ENST00000515242:+:e1
chr1	11873	12226	DDX11L1:ENST00000518655:+:e1
chr1	12009	12056	DDX11L1:ENST00000450305:+:e1
chr1	12057	12177	DDX11L1:ENST00000450305:+:i1
chr1	12178	12226	DDX11L1:ENST00000450305:+:e2
chr1	12227	12593	DDX11L1:ENST00000518655:+:i1

Specifically we extracted information above from Homo_sapiens.GRCh37.75.gtf to make the E75_bed file. But you can modify misplice accordingly if you want it to take in different information.

p.s. keep an eye on what genome build you are using and whether the gene annotation info is 0 or 1 based.

Hope that helps,
Reyka

**Comment by jfass** [comment]
Hi Reyka, could you elaborate some more on the format of the E75 bed file? I can't download from the Google Drive link ("Secure Connection Failed"), so I was going to recreate the E75 bed file. But from your example above, are you annotating introns (last colon-separated field, "i#") and the number of that intron within the specified transcript? That seems non-trivial. I looked at the current closest analog of the GTF file you mention above (Homo_sapiens.GRCh38.96.gtf), and introns aren't annotated (though, I think I've seen that in some GTF files in the past ... maybe?). Do you have any code that would number introns in this way? The exons are numbered, so I could just take those numbers ... but that raises another point about your E75 bed file ... are those "e#" fields the number of the exon within the gene, or within the particular transcript?

Any guidance you could offer would be appreciated.

**Comment by reykajayasinghe** [comment]
Hi Joseph,

I tried the link again on incognito and it should work. The file is a bit too large so you wont see a preview you will just need to click the download link (https://drive.google.com/file/d/14vHI3G45c-xBzpgzs_I43orrKbNJyIVi/view). Otherwise please shoot me an email at reyka@wustl.edu and I can email it to you.

But you are correct that the #i is indicating introns and the #e is indicating exons. We modified a GTF file from UCSC to fit our purposes, but I will need to go back to look at a few files to see how we did this. I wonder if new versions no longer do this? I don't personally have a code that can alter the input file in the way you are suggesting but I can look into it a bit more as we are also updating to GRCh38 for future runs. I will update you as we update our input files. 

Hope this helps please let me know if you have any further questions.

Best,
Reyka

**Comment by jfass** [comment]
Huh. Still doesn't work at all for me, but could be corporate internet blockage. I'll email you, thanks.

**Comment by jfass** [comment]
Got it-- thank you. A mysterious combination of my VPN, company wireless,
and planetary alignment was required.
~Joe
